config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'use', to: 'static_pages#use'
  get '/after_login', to: 'static_pages#after_login', as: 'after_login'
  # LINEログイン関連のルーティング
  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
  delete 'line_login_api/destroy', to: 'line_login_api#destroy'
  # LINEのWebhookイベントを受け取るエンドポイント
  post 'line_webhooks/callback', to: 'line_webhooks#callback'
  resources :okotos, only: %i[index] do
    collection do
      get 'plays'
    end
  end
  resources :diagnoses
  resources :results, only: %i[index new create show] do
    collection do
      get 'ranks'
    end
    resources :videos do
      resources :favorites, only: %i[create destroy]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

# This controller handles static pages.
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top terms use]

  def top; end

  def terms; end

  def after_login; end

  def use; end
end

app/views/static_pages/after_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>おこと診断 ログイン後</title>
  </head>
  <body>
    <div class="bg-mobile1 md:bg-desktop1 bg-cover bg-center w-full h-screen">
      <div class="container mx-auto text-center">  
      <header class="p-4">
        <div class="container mx-auto text-center">
          <img src="<%= asset_path('kotosin.png') %>" class="mx-auto" style="width: 500px;" />
        </div>
      </header>

        <div class="p-4">
          <div class="container mx-auto text-center">
            <%= link_to '診断スタート', diagnoses_path, class: "btn bg-silver" %>
            <h1 class="text-2xl p-4 font-bold">おことの情報</h1>
            <%= link_to "ことについて", okotos_path, class: "btn bg-silver " %>
            <%= link_to "おことの演奏技法", plays_okotos_path, class: "btn bg-silver" %>
            <h2 class="text-2xl p-4 font-bold">ランキング</h2>
            <%= link_to "ランキング", ranks_results_path, class: "btn bg-silver mb-4" %> 
          </div>        
            <div class="btn bg-secondary-content"> <!-- 余白を追加 -->
            <%= link_to "https://twitter.com/share?url=https://www.okotoshindan.com/&text=【お箏診断】診断をしてあなたの聞きたいお箏の曲を聞けます♪お箏の曲は眠たくない曲もたくさんありますよ！！", target: '_blank', title: "Xでシェア" do %>
              Xでシェアする
            <% end %>
            </div>
          <div class="w-full flex justify-center p-4">
            <div id="line-button-container" class="line-it-button ml-4" data-lang="ja" data-type="friend" data-env="REAL" data-lineId="@501hrlmq" style="display: block;"></div>
            <script src="https://www.line-website.com/social-plugins/js/thirdparty/loader.min.js" async="async" defer="defer"></script>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/static_pages/terms.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>利用規約</title>
</head>
<body>
  <div class="container">
      <h1>利用規約</h1>
      <p>この利用規約（以下，「本規約」といいます。）は，お箏診断（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>

      <h2>第1条（適用）</h2>
      <p>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</p>

      <h2>第2条（利用登録）</h2>
      <p>本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこれを承認することによって，利用登録が完了するものとします。当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</p>
      <ol>
          <li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
          <li>本規約に違反したことがある者からの申請である場合</li>
          <li>その他，当社が利用登録を相当でないと判断した場合</li>
      </ol>

      <h2>第3条（ユーザーIDおよびパスワードの管理）</h2>
      <p>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。</p>

      <h2>第4条（利用料金および支払方法）</h2>
      <p>ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。</p>

      <h2>第5条（禁止事項）</h2>
      <p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
      <ol>
          <li>法令または公序良俗に違反する行為</li>
          <li>犯罪行為に関連する行為</li>
          <li>本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為</li>
          <li>当社，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
          <li>本サービスによって得られた情報を商業的に利用する行為</li>
          <li>当社のサービスの運営を妨害するおそれのある行為</li>
          <li>不正アクセスをし，またはこれを試みる行為</li>
          <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
          <li>不正な目的を持って本サービスを利用する行為</li>
          <li>本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為</li>
          <li>他のユーザーに成りすます行為</li>
          <li>当社が許諾しない本サービス上での宣伝，広告，勧誘，または営業行為</li>
          <li>面識のない異性との出会いを目的とした行為</li>
          <li>当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
          <li>その他，当社が不適切と判断する行為</li>
      </ol>

			<h2>第6条（本サービスの提供の停止等）</h2>
				<p>当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</p>
			<ol>
				<li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
				<li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
				<li>コンピュータまたは通信回線等が事故により停止した場合</li>
				<li>その他，当社が本サービスの提供が困難と判断した場合</li>
			</ol>
				<p>当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</p>

      <h2>第7条（利用制限および登録抹消）</h2>
        <ol>
					<li>当社は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。
						<ol>
							<li>本規約のいずれかの条項に違反した場合</li>
							<li>登録事項に虚偽の事実があることが判明した場合</li>
							<li>料金等の支払債務の不履行があった場合</li>
							<li>当社からの連絡に対し，一定期間返答がない場合</li>
							<li>本サービスについて，最終の利用から一定期間利用がない場合</li>
							<li>その他，当社が本サービスの利用を適当でないと判断した場合</li>
						</ol>
					</li>
					<li>当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
        </ol>
      <h2>第8条（退会）</h2>
      	<p>ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。</p>
      <h2>第9条（保証の否認および免責事項）</h2>
				<ol>
					<li>当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
					<li>当社は，本サービスに起因してユーザーに生じたあらゆる損害について、当社の故意又は重過失による場合を除き、一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</li>
					<li>前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
					<li>当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
				</ol>
      <h2>第10条（サービス内容の変更等）</h2>
      	<p>当社は，ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。</p>
      <h2>第11条（利用規約の変更）</h2>
      	<ol>
					<li>当社は以下の場合には、ユーザーの個別の同意を要せず、本規約を変更することができるものとします。
						<ol>
							<li>本規約の変更がユーザーの一般の利益に適合するとき。</li>
							<li>本規約の変更が本サービス利用契約の目的に反せず、かつ、変更の必要性、変更後の内容の相当性その他の変更に係る事情に照らして合理的なものであるとき。</li>
						</ol>
					</li>
					<li>当社はユーザーに対し、前項による本規約の変更にあたり、事前に、本規約を変更する旨及び変更後の本規約の内容並びにその効力発生時期を通知します。</li>
				</ol>
      <h2>第12条（個人情報の取扱い）</h2>
      	<p>当社は，本サービスの利用によって取得する個人情報については，当社「プライバシーポリシー」に従い適切に取り扱うものとします。</p>
      <h2>第13条（通知または連絡）</h2>
      	<p>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>
      <h2>第14条（権利義務の譲渡の禁止）</h2>
      	<p>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>
      <h2>第15条（準拠法・裁判管轄）</h2>
      	<ol>	
					<li>本規約の解釈にあたっては，日本法を準拠法とします。</li>
					<li>本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
				</ol>
      <p class="tR">以上</p>
  </div>
</body>

app/views/static_pages/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>おこと診断</title>
  </head>
  <body>
    <div class="bg-mobile1 md:bg-desktop1 bg-cover bg-center w-full h-screen">
      <div class="container mx-auto text-center">   
      <header class="p-4">
        <div class="container mx-auto text-center">
          <img src="<%= asset_path('kotosin.png') %>" class="mx-auto" style="width: 500px;" />
        </div>
      </header>

        <div class="p-4">
          <div class="container mx-auto text-center">
            <%= link_to '診断スタート', diagnoses_path, class: "btn bg-silver" %>
            <h1 class="text-2xl p-4 font-bold">おことの情報</h1>
            <%= link_to "ことについて", okotos_path, class: "btn bg-silver" %>
            <%= link_to "おことの演奏技法", plays_okotos_path, class: "btn bg-silver" %>
            <h2 class="text-2xl p-4 font-bold">ランキング</h2>
            <%= link_to "ランキング", ranks_results_path, class: "btn bg-silver mb-4" %>
            <div class="w-full flex justify-center p-4">
            <div class="btn bg-secondary-content ">
            <%= link_to "https://twitter.com/share?url=https://www.okotoshindan.com/&text=【お箏診断】診断をしてあなたの聞きたいお箏の曲を聞けます♪お箏の曲は眠たくない曲もたくさんありますよ！！", 
              target: '_blank', title: "Xでシェア" do %>
              Xでシェアする
            <% end %>
            </div>
            <%= link_to "LINEでログイン", line_login_api_login_path, class: "btn bg-line mb-4" %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/static_pages/use.html.erb
<div style="background-image: url('<%= asset_path('umeki.png') %>'); background-repeat: repeat;">
  <div class="container mx-auto text-center">
    <div class="p-4">
      <h1 class="text-4xl p-4">アプリの使い方</h1>
      <p class="text-2xl p-4">診断スタートを押して聞きたいジャンルを選びます</p>
      <a href="https://gyazo.com/c752abcc59415599afb056066ecdbac9">
        <img src="https://i.gyazo.com/c752abcc59415599afb056066ecdbac9.gif" alt="Image from Gyazo" class="mx-auto w-[300px] sm:w-[500px]"/>
      </a>
      <h2 class="text-4xl p-4">ログイン後にできること</h2>
      <p class="text-2xl p-4">１　ラインの友達登録をして通知を受け取る</p>
      <img src="/assets/botannn.png" class="mx-auto w-[300px] sm:w-[500px]" />
      <p class="text-2xl p-4">２　良きボタンをおしてランキングに反映（良きボタンはログイン後にしかでてきません）</p>
      <a href="https://gyazo.com/28add6c5b5006e62fd8c53b7c8b9ddc7">
      <img src="https://i.gyazo.com/28add6c5b5006e62fd8c53b7c8b9ddc7.gif" alt="Image from Gyazo", class="mx-auto w-[300px] sm:w-[500px]"/></a>
      <div class="mt-4">
        <% if logged_in? %>  <!-- ユーザーがログインしているか確認 -->
          <%= link_to 'トップページに戻る', after_login_path, class: "btn bg-silver" %>
        <% else %>
          <%= link_to 'トップページに戻る', root_path, class: "btn bg-silver" %>
        <% end %>
      </div>      
    </div>
  </div>
</div>