config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'use', to: 'static_pages#use'
  get '/after_login', to: 'static_pages#after_login', as: 'after_login'
  # LINEログイン関連のルーティング
  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
  delete 'line_login_api/destroy', to: 'line_login_api#destroy'
  # LINEのWebhookイベントを受け取るエンドポイント
  post 'line_webhooks/callback', to: 'line_webhooks#callback'
  resources :okotos, only: %i[index] do
    collection do
      get 'plays'
    end
  end
  resources :diagnoses
  resources :results, only: %i[index new create show] do
    collection do
      get 'ranks'
    end
    resources :videos do
      resources :favorites, only: %i[create destroy]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/favorite.rb
# frozen_string_literal: true

# Favorite model for storing user favorites
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :video
  belongs_to :result

  # ユーザー一人につきいいね1個まで
  validates_uniqueness_of :video_id, scope: :user_id
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

# Represents the controller for Favorites.
class FavoritesController < ApplicationController
  before_action :require_login

  def create
    @video = Video.find(params[:video_id])
    @result = @video.result
    @favorite = current_user.favorites.find_or_initialize_by(video: @video)
    @favorite.result_id = @result.id

    if @favorite.save
      respond_to :turbo_stream
    else
      respond_to do |format|
        format.html { redirect_to @result, alert: 'Failed to favorite.' }
      end
    end
  end

  def destroy
    @video = Video.find(params[:video_id])
    @result = @video.result
    @favorite = current_user.favorites.find_by(video: @video)

    if @favorite.destroy
      respond_to :turbo_stream
    else
      respond_to do |format|
        format.html { redirect_to @result, alert: 'Failed to unfavorite.' }
      end
    end
  end
end

app/views/favorites/_favorite_button.html.erb
<% if @favorite.present? && current_user.already_favorited?(video) %>
  <%= button_to "良き", result_video_favorite_path(result_id: @result.id, video_id: video.id, id: @favorite.id), method: :delete, remote: true, data: { turbo_method: :delete}, id: "favorite-button-container-#{video.id}", class: "btn bg-good" %>
<% else %>
  <%= button_to "良き", result_video_favorites_path(result_id: @result.id, video_id: video.id), method: :post, remote: true, data: { turbo_method: :post}, id: "favorite-button-container-#{video.id}", class: "btn bg-ungood" %>
<% end %>

app/views/favorites/create.turbo_stream.erb
<%= turbo_stream.update "favorite-button-container-#{@video.id}" do %>
  <%= render partial: "favorite_button", locals: { video: @video, result: @result} %>
<% end %>

app/views/favorites/destroy.turbo_stream.erb
<%= turbo_stream.update "favorite-button-container-#{@video.id}" do %>
  <%= render partial: "favorite_button", locals: { video: @video, result: @result } %>
<% end %>