config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'use', to: 'static_pages#use'
  get '/after_login', to: 'static_pages#after_login', as: 'after_login'
  # LINEログイン関連のルーティング
  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
  delete 'line_login_api/destroy', to: 'line_login_api#destroy'
  # LINEのWebhookイベントを受け取るエンドポイント
  post 'line_webhooks/callback', to: 'line_webhooks#callback'
  resources :okotos, only: %i[index] do
    collection do
      get 'plays'
    end
  end
  resources :diagnoses
  resources :results, only: %i[index new create show] do
    collection do
      get 'ranks'
    end
    resources :videos do
      resources :favorites, only: %i[create destroy]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/diagnoses_controller.rb
# frozen_string_literal: true

# Represents the controller for Diagnoses.
class DiagnosesController < ApplicationController
  skip_before_action :require_login
  def index
    @diagnosis = Diagnosis.all
  end

  def new
    @diagnosis = Diagnosis.new
  end

  def show
    @diagnosis = Diagnosis.find_by(id: params[:id])
  end

  def create
    @diagnosis = Diagnosis.new(diagnosis_params)
    # params[:topic][:question] ? @topic.question = params[:topic][:question].join("") : false
    if @diagnosis.save
      flash[:notice] = '診断が完了しました'
      redirect_to diagnosis_path(@diagnosis.id)
    else
      redirect_to action: 'new'
    end
  end

  private

  def diagnosis_params
    params.require(:diagnosis).permit(:title)
  end
end

app/views/diagnoses/index.html.erb
<div class="bg-mobile2 md:bg-desktop2 bg-cover bg-center w-full h-screen">
<div class="p-4">
<div class="container mx-auto text-center">
  <%= form_with model: @diagnosis, url: diagnoses_path, local: true do |form| %>
    <% form.hidden_field :id %>
    <% form.text_field :title %>
    <div class="text-center">
    <h3 class="text-xl p-4">Q.1 どちらの音楽がききたいですか？</h3>
    </div>
    <% Diagnosis.where(id: [1, 2]).each do |diagnosis| %>
      <label>
        <%= link_to diagnosis.title, diagnosis_path(id: diagnosis.id), class: "btn bg-silver" %>
      </label>
    <% end %>
  <% end %>
</div>
</div>
</div>
 

app/views/diagnoses/show.html.erb
<div class="bg-mobile2 md:bg-desktop2 bg-cover bg-center w-full h-screen">
<div class="p-4">
<div class="container mx-auto text-center">
<% if params[:id] == "1" %>
  <h3 class="text-xl p-4">Q.2 次にどちらの音楽がききたいですか？</h3>

  <% Diagnosis.where(id: [3, 4, 5]).each do |diagnosis| %>
    <label>
      <% if diagnosis.id == 3 %>
        <%= link_to diagnosis.title, result_path(1), class: "btn bg-silver" %>
      <% elsif diagnosis.id == 4 %>
        <%= link_to diagnosis.title, result_path(2), class: "btn bg-silver" %>
      <% elsif diagnosis.id == 5 %>
        <%= link_to diagnosis.title, diagnosis_path(id: diagnosis.id),class: "btn bg-silver" %>
      <% end %>
    </label>
  <% end %>

<% elsif params[:id] == "2" %>
  <h3 class="text-xl p-4">Q.2 次にどちらの音楽がききたいですか？</h3>

  <% Diagnosis.where(id: [6, 7]).each do |diagnosis| %>
    <label>
      <% if diagnosis.id == 6 %>
        <%= link_to diagnosis.title, result_path(6), class: "btn bg-silver" %>
      <% elsif diagnosis.id == 7 %>
        <%= link_to diagnosis.title, result_path(7), class: "btn bg-silver" %>
      <% end %> <!-- ここを修正してendを追加 -->
    </label>
  <% end %>

<% elsif params[:id] == "5" %>
  <h3 class="text-xl p-4">Q.3 最後にどちらの音楽がききたいですか？</h3>

  <% Diagnosis.where(id: [8, 9, 10]).each do |diagnosis| %>
    <label>
      <% if diagnosis.id == 8 %>
        <%= link_to diagnosis.title, result_path(3), class: "btn bg-silver" %>
      <% elsif diagnosis.id == 9 %>
        <%= link_to diagnosis.title, result_path(4), class: "btn bg-silver" %>
      <% elsif diagnosis.id == 10 %>
        <%= link_to diagnosis.title, result_path(5), class: "btn bg-silver" %>
      <% end %> <!-- ここもendを追加 -->
    </label>
  <% end %>
<% end %>
</div>
</div>
</div>