config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'use', to: 'static_pages#use'
  get '/after_login', to: 'static_pages#after_login', as: 'after_login'
  # LINEログイン関連のルーティング
  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
  delete 'line_login_api/destroy', to: 'line_login_api#destroy'
  # LINEのWebhookイベントを受け取るエンドポイント
  post 'line_webhooks/callback', to: 'line_webhooks#callback'
  resources :okotos, only: %i[index] do
    collection do
      get 'plays'
    end
  end
  resources :diagnoses
  resources :results, only: %i[index new create show] do
    collection do
      get 'ranks'
    end
    resources :videos do
      resources :favorites, only: %i[create destroy]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_before_login_header.html.erb
<header>
  <div class="bg-pinku flex flex-row justify-between items-center w-full h-16">
    <div class="pl-4">
    <%= link_to root_path do %>
      <%= image_tag 'kotosin.png', class: 'w-32 h-15 md:w-48 md:h-22' %>
    <% end %>
    </div>
            
    <div class="dropdown dropdown-end ">
      <div tabindex="0" role="button" class="flex items-center py-2 px-4 text-sm btn m-1 mr-4">
        <span class="material-symbols-outlined">menu</span>
      </div>
      <ul tabindex="0" class="dropdown-content menu z-[2] w-52 p-2 shadow">
        <%= link_to 'アプリの使い方', use_path, class: "btn bg-silver" %>
        <%= link_to "LINEでログイン", line_login_api_login_path, class: "btn bg-line mb-4" %>
      </ul>
    </div>      
  </div>
</header>

app/views/shared/_footer.html.erb
<footer> 
  <div class="bg-pinku flex flex-col justify-between items-center h-24 content-end"> 
      <!-- nav - start --> 
      <nav class="flex flex-wrap justify-center gap-x-4 gap-y-2 md:justify-start mt-6 "> 
      <%= link_to '利用規約', terms_path %> 
      <%= link_to "プライバシーポリシー", "https://kiyac.app/privacypolicy/TFsYGgdJsfcijdNYSQlB", target: "_blank", rel: "noopener" %> 
      <%= link_to "お問い合わせ", "https://docs.google.com/forms/d/e/1FAIpQLScYTq6SwmWJ4tx2pL3SCVIVtnz2HVyGQXdsFK83WwDXi_WnKA/viewform?embedded=true", target: "_blank", rel: "noopener" %> 
      </nav> 
      <!-- nav - end --> 
    <div class="text-center text-sm text-teal-950 mb-2"> Copyright © 2024 - お箏診断</div> 
  </div> 
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="bg-pinku flex flex-row justify-between items-center  text-white w-full h-16">
    <div class="pl-4">
      <%= link_to after_login_path do %>
        <%= image_tag 'kotosin.png', class: 'w-32 h-15 md:w-48 md:h-22' %>
      <% end %>
    </div>
                    
    <div class="dropdown dropdown-end ">
      <div tabindex="0" role="button" class="flex items-center py-2 px-4 text-sm btn m-1 mr-4">
        <span class="material-symbols-outlined">menu</span>
      </div>
      <ul tabindex="0" class="dropdown-content menu z-[2] w-52 p-2 shadow">
        <li class="bg-pinku rounded"><a>ID: <%= current_user.id %></a></li>
        <li class="bg-pinku rounded"><a>LINEユーザー名: <%= current_user.name %></a></li>
        <%= link_to 'アプリの使い方', use_path, class: "btn bg-silver" %>
        <%= link_to 'ログアウト', line_login_api_destroy_path, data: { turbo_method: :delete }, class: "btn bg-line" %>
        <% current_user = User.find_by(id: session[:user_id]) %>
      </ul>
    </div>      
  </div>
</header>